trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'karcagtamas/ceg-backend'
  dockerRegistryServiceConnection: 'Docker'

steps:
  - script: |
      sudo apt-get update
    displayName: 'Update packages'

  - script: |
      sudo apt-get install make -y
    displayName: 'Install Make'

  - script: |
      make gradle-build-lin
      make gradle-build-graph-model-lin
    displayName: Build Backend and graph-model library
    workingDirectory: '$(System.DefaultWorkingDirectory)/backend'

  - task: Docker@2
    inputs:
      containerRegistry: '$(dockerRegistryServiceConnection)'
      repository: '$(imageName)'
      command: 'buildAndPush'
      Dockerfile: 'backend/Dockerfile'
      tags: |
        $(Build.BuildId)

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/backend/build/install/CauseEffectGraph-shadow'
      contents: '**/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)/application'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/backend/language-server'
      contents: '**/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)/language-server'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/backend/libs/graph-model/build/libs'
      contents: '**/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)/libs/graph-model'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/application'
      artifact: 'application'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/language-server'
      artifact: 'language-server'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/libs/graph-model'
      artifact: 'graph-model'
