trigger:
  - main
  - dev
  - zv

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      sudo apt-get update
    displayName: 'Update packages'

  - script: |
      sudo apt-get install texlive -y
      sudo apt-get install texlive-latex-extra -y
      sudo apt-get install texlive-bibtex-extra -y
      sudo apt-get install texlive-science -y
      sudo apt-get install texlive-font-utils -y
      sudo apt-get install texlive-lang-european -y
      sudo apt-get install texlive-fonts-extra -y
      sudo apt-get install biber -y
    displayName: 'Install LaTeX'

  - script: |
      sudo apt-get install make -y
    displayName: 'Install Make'

  - script: |
      make convert
    displayName: Convert documentation to PDF
    workingDirectory: '$(System.DefaultWorkingDirectory)/docs'

  - script: |
      make convert
    displayName: Convert presentation to PDF
    workingDirectory: '$(System.DefaultWorkingDirectory)/zv'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/docs/thesis.pdf'
      artifact: 'docs'
      publishLocation: 'pipeline'
    displayName: 'Publish Artifact'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/zv'
      artifact: 'zv'
      publishLocation: 'pipeline'
    displayName: 'Publish Presentation Artifact'
